# Generated by Django 5.1.7 on 2025-04-11 19:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type_consultation', models.CharField(choices=[('INITIALE', 'Consultation initiale'), ('SUIVI', 'Consultation de suivi'), ('URGENCE', "Consultation d'urgence")], max_length=10)),
                ('symptomes', models.TextField(blank=True)),
                ('diagnostic', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_realisation', models.DateField()),
                ('urgence', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200)),
                ('posologie', models.CharField(max_length=200)),
                ('duree_traitement', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('instructions', models.TextField(blank=True, null=True)),
                ('est_convertie', models.BooleanField(default=False)),
                ('date_conversion', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevue', models.DateTimeField()),
                ('motif', models.TextField()),
                ('notes_preparation', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('ANNULE', 'Annulé'), ('COMPLETE', 'Complété')], default='PLANIFIE', max_length=20)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_planifiees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
