# Generated by Django 5.1.7 on 2025-04-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes_preparation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
