# Generated by Django 5.1.7 on 2025-04-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_appointment_notes_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
