# Generated by Django 5.1.7 on 2025-04-02 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type_etape', models.CharField(choices=[('EXAMEN', 'Examen médical'), ('CONSULTATION', 'Consultation'), ('TRAITEMENT', 'Ajustement traitement'), ('EDUCATION', 'Éducation patient'), ('AUTRE', 'Autre action')], max_length=15)),
                ('delai_jours', models.IntegerField(help_text="Délai en jours après l'étape précédente ou le début du workflow")),
                ('periodique', models.BooleanField(default=False)),
                ('periodicite_jours', models.IntegerField(blank=True, help_text='Pour les actions périodiques, intervalle en jours', null=True)),
                ('ordre', models.IntegerField()),
            ],
            options={
                'ordering': ['workflow', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='PatientWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EtapePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevue', models.DateField()),
                ('statut', models.CharField(choices=[('PROGRAMMEE', 'Programmée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PROGRAMMEE', max_length=15)),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_assignees', to=settings.AUTH_USER_MODEL)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='workflows.etapeworkflow')),
                ('patient_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='workflows.patientworkflow')),
            ],
            options={
                'ordering': ['date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('stade_mrc', models.IntegerField(blank=True, choices=[(1, 'Stade 1'), (2, 'Stade 2'), (3, 'Stade 3'), (4, 'Stade 4'), (5, 'Stade 5')], null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
            },
        ),
        migrations.AddField(
            model_name='patientworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='etapeworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='workflows.workflow'),
        ),
    ]
