services:
  - type: web
    name: nephto-care-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mrc_platform.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db-django
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
