export { default as SearchForm } from './forms/SearchForm.vue'
export { default as ConsultationsTable } from './tables/ConsultationsTable.vue'
export { default as NewConsultationModal } from './modals/NewConsultationModal.vue'
export { default as ViewConsultationModal } from './modals/ViewConsultationModal.vue'
export { default as EditConsultationModal } from './modals/EditConsultationModal.vue'

export { default as PatientStep } from './steps/PatientStep.vue'
export { default as ConsultationDetailsStep } from './steps/ConsultationDetailsStep.vue'
export { default as PrescriptionsStep } from './steps/PrescriptionsStep.vue'
export { default as ExamenStep } from './steps/ExamenStep.vue'
export { default as AppointmentStep } from './steps/AppointmentStep.vue'

export { default as ModalHeader } from './shared/ModalHeader.vue'
export { default as ProgressBar } from './shared/ProgressBar.vue'
export { default as ModalFooter } from './shared/ModalFooter.vue'
export { default as Pagination } from './shared/Pagination.vue'
export { default as Toast } from './shared/Toast.vue'
export { default as ConfirmationDialog } from './shared/ConfirmationDialog.vue'