# Generated by Django 5.1.7 on 2025-04-02 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('stade_mrc', models.IntegerField(blank=True, choices=[(1, 'Stade 1'), (2, 'Stade 2'), (3, 'Stade 3'), (4, 'Stade 4'), (5, 'Stade 5')], null=True)),
                ('dfu', models.FloatField(blank=True, null=True, verbose_name='Débit de Filtration Urinaire')),
                ('antecedents_medicaux', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('medecin_referent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='ResultatExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(max_length=200)),
                ('date_realisation', models.DateField()),
                ('laboratoire', models.CharField(blank=True, max_length=200)),
                ('resultats_texte', models.TextField(blank=True)),
                ('fichier_resultats', models.FileField(blank=True, null=True, upload_to='resultats_examens/')),
                ('creatinine', models.FloatField(blank=True, null=True)),
                ('dfu', models.FloatField(blank=True, null=True, verbose_name='Débit de Filtration Urinaire')),
                ('proteinurie', models.FloatField(blank=True, null=True)),
                ('interpretation', models.TextField(blank=True, help_text='Interprétation médicale des résultats')),
                ('est_anormal', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('examen_prescrit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_examen_prescrit+', to='consultations.examen')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_examens', to='patients.patient')),
            ],
            options={
                'ordering': ['-date_realisation'],
            },
        ),
        migrations.CreateModel(
            name='TraitementEnCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200)),
                ('posologie', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='patients.patient')),
                ('prescripteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescription_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements_resultants', to='consultations.prescription')),
                ('traitement_precedent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitement_suivant', to='patients.traitementencours')),
            ],
        ),
    ]
