# Generated by Django 5.1.7 on 2025-04-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultatexamen',
            name='interpretation',
            field=models.TextField(blank=True, help_text='Interprétation médicale des résultats', null=True),
        ),
        migrations.AlterField(
            model_name='resultatexamen',
            name='laboratoire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resultatexamen',
            name='resultats_texte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
